"""Beacon management — create beacons and hand out the firmware secret."""

from __future__ import annotations

from typing import Any

from app.core.config import get_settings
from app.core.exceptions import NotFoundError
from app.repositories.beacon_repo import BeaconRepository
from app.schemas.requests import BeaconCreate, BeaconUpdate
from app.security.auth import CurrentStaff
from app.services.attempt_service import audit
from app.services.beacon_token import new_secret

_repo = BeaconRepository()


def public_beacon(row: dict[str, Any]) -> dict[str, Any]:
    """Beacon without its secret."""
    return {k: v for k, v in row.items() if k != "secret"}


def firmware_config(row: dict[str, Any]) -> str:
    """Ready-to-paste contents for firmware/staff_beacon/secrets.h."""
    return (
        "// firmware/staff_beacon/secrets.h — generated by the backend\n"
        '#define WIFI_SSID      "your-campus-wifi"\n'
        '#define WIFI_PASSWORD  "your-wifi-password"\n'
        f'#define BEACON_ID      "{row["id"]}"\n'
        f'#define BEACON_SECRET  "{row["secret"]}"\n'
        f'#define BEACON_NAME    "SCA-{_short_name(row.get("name", ""))}"\n'
        f"#define TOKEN_WINDOW_SECONDS {get_settings().beacon_window_seconds}\n"
    )


def _short_name(name: str) -> str:
    cleaned = "".join(c for c in name.upper() if c.isalnum())
    return (cleaned or "BEACON")[:12]


def with_secret(row: dict[str, Any]) -> dict[str, Any]:
    """Beacon including secret + firmware snippet (admin only)."""
    return {**row, "firmware_config": firmware_config(row)}


def list_beacons() -> list[dict[str, Any]]:
    """All beacons without secrets."""
    return [public_beacon(b) for b in _repo.list_beacons()]


def _get(beacon_id: str) -> dict[str, Any]:
    row = _repo.get_by_id(beacon_id)
    if row is None:
        raise NotFoundError("Beacon", beacon_id)
    return row


def create(admin: CurrentStaff, req: BeaconCreate) -> dict[str, Any]:
    """Register a beacon and return its secret once."""
    row = _repo.insert({**req.model_dump(), "secret": new_secret(), "is_active": True})
    audit(admin.id, "beacon_create", None, beacon_id=row["id"], name=row["name"])
    return with_secret(row)


def get_secret(admin: CurrentStaff, beacon_id: str) -> dict[str, Any]:
    """Show the secret again (e.g. to re-flash a beacon)."""
    row = _get(beacon_id)
    audit(admin.id, "beacon_view_secret", None, beacon_id=beacon_id)
    return with_secret(row)


def update(admin: CurrentStaff, beacon_id: str, req: BeaconUpdate) -> dict[str, Any]:
    """Edit name/location/threshold/active."""
    _get(beacon_id)
    data = req.model_dump(exclude_none=True)
    row = _repo.update(beacon_id, data) if data else _get(beacon_id)
    audit(admin.id, "beacon_update", None, beacon_id=beacon_id, changes=data)
    return public_beacon(row)


def rotate_secret(admin: CurrentStaff, beacon_id: str) -> dict[str, Any]:
    """Issue a new secret (the beacon must be re-flashed)."""
    _get(beacon_id)
    row = _repo.update(beacon_id, {"secret": new_secret()})
    audit(admin.id, "beacon_rotate_secret", None, beacon_id=beacon_id)
    return with_secret(row)
